// <auto-generated />
using System;
using CuentasPorCobrar.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(CuentasporcobrardbContext))]
    partial class CuentasporcobrardbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuentasPorCobrar.Shared.AccountingEntry", b =>
                {
                    b.Property<int>("AccountingEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountingEntryId"));

                    b.Property<int>("Account")
                        .HasColumnType("int");

                    b.Property<decimal>("AccountEntryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AccountEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovementType")
                        .HasColumnType("int");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.HasKey("AccountingEntryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AccountingEntries");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("money");

                    b.Property<string>("Identification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LedgerAccount")
                        .HasColumnType("int");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("AccountingEntryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<Guid?>("DocumentNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MovementType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountingEntryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.AccountingEntry", b =>
                {
                    b.HasOne("CuentasPorCobrar.Shared.Customer", "Customer")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Transaction", b =>
                {
                    b.HasOne("CuentasPorCobrar.Shared.AccountingEntry", "AccountingEntry")
                        .WithMany()
                        .HasForeignKey("AccountingEntryId");

                    b.HasOne("CuentasPorCobrar.Shared.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CuentasPorCobrar.Shared.Document", "Document")
                        .WithMany("Transactions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AccountingEntry");

                    b.Navigation("Customer");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Customer", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CuentasPorCobrar.Shared.Document", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
